"""empty message

Revision ID: 3232ed28d648
Revises: 573d0da0bcbe
Create Date: 2024-05-13 01:10:44.213242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3232ed28d648'
down_revision: Union[str, None] = '573d0da0bcbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_User_User_Instagram_ID', table_name='User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_User_User_Instagram_ID', 'User', ['User_Instagram_ID'], unique=True)
    # ### end Alembic commands ###
