"""empty message

Revision ID: 5d8b600108f3
Revises: c0ab76b42eb6
Create Date: 2024-06-03 15:35:07.807316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d8b600108f3'
down_revision: Union[str, None] = 'c0ab76b42eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Clothes', 'Clothes_Color',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.drop_column('Clothes', 'Clothes_Tone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clothes', sa.Column('Clothes_Tone', mysql.VARCHAR(length=20), nullable=True))
    op.alter_column('Clothes', 'Clothes_Color',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    # ### end Alembic commands ###
