"""empty message

Revision ID: 766309cce1a8
Revises: 15ff2e1278c0
Create Date: 2024-05-11 21:09:50.611137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '766309cce1a8'
down_revision: Union[str, None] = '15ff2e1278c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('User_NickName', sa.String(length=20), nullable=False),
    sa.Column('User_Instagram_ID', sa.String(length=50), nullable=True),
    sa.Column('User_Age', sa.Integer(), nullable=True),
    sa.Column('User_ProfileImage', mysql.LONGBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('username', name=op.f('pk_User')),
    sa.UniqueConstraint('User_Instagram_ID', name=op.f('uq_User_User_Instagram_ID')),
    sa.UniqueConstraint('User_NickName', name=op.f('uq_User_User_NickName')),
    sa.UniqueConstraint('username', name=op.f('uq_User_username'))
    )
    op.create_table('Clothes',
    sa.Column('Clothes_Id', sa.Integer(), nullable=False),
    sa.Column('Clothes_Create_Date', sa.DateTime(), nullable=False),
    sa.Column('Clothes_LastFit_Date', sa.DateTime(), nullable=False),
    sa.Column('Clothes_Category', sa.String(length=50), nullable=True),
    sa.Column('Clothes_Image', mysql.LONGBLOB(), nullable=False),
    sa.Column('Clothes_Count', sa.Integer(), nullable=True),
    sa.Column('Clothes_Score', sa.Integer(), nullable=True),
    sa.Column('User_Id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['User_Id'], ['User.username'], name=op.f('fk_Clothes_User_Id_User')),
    sa.PrimaryKeyConstraint('Clothes_Id', name=op.f('pk_Clothes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Clothes')
    op.drop_table('User')
    # ### end Alembic commands ###
