"""empty message

Revision ID: 911de5900da0
Revises: 5d8b600108f3
Create Date: 2024-06-10 16:16:27.857439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '911de5900da0'
down_revision: Union[str, None] = '5d8b600108f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Clothes', 'Clothes_Score',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.PickleType(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Clothes', 'Clothes_Score',
               existing_type=sa.PickleType(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
