"""empty message

Revision ID: 9966bd3d5dd4
Revises: 16326ec2dae9
Create Date: 2024-04-30 02:52:53.343791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9966bd3d5dd4'
down_revision: Union[str, None] = '16326ec2dae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.Column('instagram', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('instagram', name=op.f('uq_user_instagram')),
    sa.UniqueConstraint('nickname', name=op.f('uq_user_nickname')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', mysql.LONGBLOB(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_member_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    op.drop_table('user')
    # ### end Alembic commands ###
