"""empty message

Revision ID: c0ab76b42eb6
Revises: 3232ed28d648
Create Date: 2024-05-15 11:18:10.449149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ab76b42eb6'
down_revision: Union[str, None] = '3232ed28d648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clothes', sa.Column('Clothes_Color', sa.String(length=7), nullable=True))
    op.add_column('Clothes', sa.Column('Clothes_Tone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Clothes', 'Clothes_Tone')
    op.drop_column('Clothes', 'Clothes_Color')
    # ### end Alembic commands ###
