"""empty message

Revision ID: c67a7cb2357f
Revises: 499a19404406
Create Date: 2024-04-11 14:31:18.403231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67a7cb2357f'
down_revision: Union[str, None] = '499a19404406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userid', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('instagram', sa.String(length=50), nullable=True))
    op.create_unique_constraint(op.f('uq_user_instagram'), 'user', ['instagram'])
    op.create_unique_constraint(op.f('uq_user_userid'), 'user', ['userid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_userid'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_user_instagram'), 'user', type_='unique')
    op.drop_column('user', 'instagram')
    op.drop_column('user', 'userid')
    # ### end Alembic commands ###
