"""empty message

Revision ID: edbd0ce01b9e
Revises: c1ade078f2e5
Create Date: 2024-03-20 13:02:39.046399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbd0ce01b9e'
down_revision: Union[str, None] = 'c1ade078f2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('image', sa.LargeBinary(), nullable=False))
    op.drop_column('member', 'content')
    op.drop_column('member', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('subject', sa.VARCHAR(), nullable=False))
    op.add_column('member', sa.Column('content', sa.TEXT(), nullable=False))
    op.drop_column('member', 'image')
    # ### end Alembic commands ###
